---
- name: Install Node and npm
  hosts: 13.48.127.209
  become: true
  tasks:
    - name: Update apt repo and cach
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600

    - name: Install nodejs and npm
      apt: 
        pkg:
          - nodejs
          - npm

- name: Deploy nodejs app
  become: true
  hosts: 13.48.127.209
  vars_files:
    - ansible-vars
  tasks:

  #  - name: Copy nodejs folder to a server
   #   copy:
    #    src: /home/youssefjh/mynodecicd/app/bootcamp-node-project-1.0.tgz 
     #   dest: /home/ubuntu/node-project-1.0.tgz 

    - name: Unpack the nodejs file
      unarchive:
        src: "{{location}}/bootcamp-node-project-{{version}}.tgz"  #/home/ubuntu/node-project-1.0.tgz 
        dest: "{{destination}}"
    - name: Install dependencies
      npm:
        path: "{{destination}}/package"
    - name: Start the app
      command: node server                 # node /home/ubuntu/package/app/serve  
      async: 1000
      poll: 0
    - name: Ensure app is running
      shell: ps aux | grep node
      register: app_status
    - debug: msg={{app_status.stdout_lines}}



    
